//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaksiProjectNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARACLAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ARACLAR()
        {
            this.CAGRILAR = new HashSet<CAGRILAR>();
        }
    
        public int ARACID { get; set; }
        public string PLAKA { get; set; }
        public string ARACSAHIBI { get; set; }
        public Nullable<decimal> ARACSAHIBITELEFON { get; set; }
        public string ACIKLAMA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAGRILAR> CAGRILAR { get; set; }
    }
}
